# Generated by Django 5.1.3 on 2024-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_pkey', models.AutoField(primary_key=True, serialize=False)),
                ('total_deaths', models.IntegerField()),
                ('total_patients', models.IntegerField()),
            ],
            options={
                'db_table': 'record',
                'managed': False,
            },
        ),
    ]
