# Generated by Django 5.1.3 on 2024-11-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_record_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'managed': False},
        ),
    ]
