# Generated by Django 5.1.3 on 2024-11-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_record_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='disease',
            table='disease',
        ),
    ]
