# Generated by Django 5.1.3 on 2024-11-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_disease_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='disease_type',
            new_name='id',
        ),
    ]
