# Generated by Django 5.1.3 on 2024-11-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_disease_type_disease_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'managed': False},
        ),
    ]
