# Generated by Django 5.1.3 on 2024-11-18 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_disease_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.users'),
        ),
        migrations.AlterModelTable(
            name='patients',
            table='patients',
        ),
    ]
