# Generated by Django 5.1.3 on 2024-11-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_patients_email_alter_patients_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(db_column='email', max_length=60, primary_key=True, serialize=False),
        ),
    ]
